### ISSUE TITLE
How is it compared to lost grid?

### ISSUE THREAD

**Issue by alexedev** [juliancwirko/s-grid#1]
Hey. Cory Simmons created a new grid system called lost. Did you try it? https://github.com/corysimmons/lost

**Comment by juliancwirko** [comment]
Yeah, Lost is super cool. I always admire all work of Cory and it is inspired by his work too.
I think my little grid system shouldn't be compared because it is in a very early stage.

But if I need to:
- I always wanted to have ready to use helper classes. I like to use Stylus functions instead in final version (and I encourage you to do that), but sometimes I need to do fast mockups. Classes like `s-grid-md-6`are very fast and useful. S-grid has helper classes and also Stylus functions. Can be used interchangeably.
- I also don't want to make it for Scss or Less users. I want it to work only with Stylus without any other Less or Scss documentation which can confuse.
- I want to work with Stylus because I want to use it with Meteor and I think that Stylus is the best for Meteor. S-Grid will be always prepared for usage with Meteor. https://atmospherejs.com/juliancwirko/s-grid (with Autoprefixer on board)
- S-grid is supposed to be one of the Meteor boilerplate components, so sometimes it is better if my own boilerplate uses my own grid system (but not always, I know ;) will be improved)

Of course I encourage you to use [Lost](https://github.com/corysimmons/lost) by @corysimmons because it is very good. I think that there is a Meteor package on Atmosphere with Lost too : https://atmospherejs.com/stolinski/stylus-multi cool! ( @stolinski could you bump Lost version? ;) btw. very good tuts by @stolinski : [Stylus, Meteor and many other](https://www.youtube.com/channel/UCyU5wkjgQYGRB0hIHMwm2Sg) ;) )

And if you want something small, simple, based on Stylus and ready to use with Meteor you should check the website: http://s-grid.meteor.com/ 
There is also Grunt scaffold: https://github.com/juliancwirko/s-grid-grunt 

@buduguru thanks for your question :)

PS. If someone is interested PR are welcomed ;)

**Comment by alexedev** [comment]
Thank you for the reply.
Yes, I like stylus and use meteor too, that is because I stumbled upon your plugin. I liked lost because it uses calc() everywhere and you can create terse markup https://github.com/corysimmons/lost/wiki/Comparison-Explanation#terse-markup 
I played a bit with the example and it seems very intuitive and easy grid to use http://codepen.io/anon/pen/QwRYXO
and thank you for @stolinski package url.

**Comment by juliancwirko** [comment]
Yes, this is cool. S-Grid also uses `calc()` and you can use Stylus functions: http://s-grid.meteor.com/#somanyuglyclasses instead of helper classes. 
I plan to do more with this :)

**Comment by alexedev** [comment]
Oh, I see, no problem then)
I will dig deeper into both systems and make final choice)

**Comment by alexedev** [comment]
btw this one looks sweat https://github.com/juliancwirko/meteor-s-alert 
will use it in my project) thanks

**Comment by corysimmons** [comment]
Neat, love this one. Good job @juliancwirko 

FWIW the next feature I'm implementing is the ability to create terse classes on the fly. And Lost supports Flexbox now as well.

**Comment by juliancwirko** [comment]
Thanks :)
