### ISSUE TITLE
Passing rem values to the gutter variable

### ISSUE THREAD

**Issue by mitramejia** [juliancwirko/s-grid#2]
If I pass rem units to the `gutter` variable on `s-grid-settings.styl` .The resulting gutter margin becomes really really small, but when pixels are passed it behaves like expected. Why is this?

Here are some screenshot from a browser console:
###### With rem units:

`gutter = (rem-calc(24))`

![localhost_3000](https://cloud.githubusercontent.com/assets/2616517/7309184/851c4c26-e9e9-11e4-939a-84a5fbe9f1c7.png)
###### With pixels:

 `gutter= 24px`

![localhost_30002](https://cloud.githubusercontent.com/assets/2616517/7309185/851f9354-e9e9-11e4-92b4-77005279cc8c.png)

**Comment by juliancwirko** [comment]
By doing this you simply do something like `rem-calc(rem-calc(24))` -> `rem-calc(1.5)` -> `0,09375rem`, Because gutter is also passed to `rem-calc()` function. So gutter should be always in `px` (for now), but I think I could make more inteligent `rem-calc()` function. I will do this asap.
Thanks for pointing it out.

**Comment by juliancwirko** [comment]
Ok now in version 1.0.1 you can pass rem values but in case of gutter config you shouldn't use `rem-calc()` function there because it is defined later in `s-grid-functions`. 

Anyway, for gutter you can use rem units now:

```
gutter = 1.5rem
```

it will also work in other .styl files in app. Usage:

```
rem-calc(24) -> 1.5rem
rem-calc(24px) -> 1.5rem
rem-calc(1.5rem) -> 1.5rem
```

**Comment by mitramejia** [comment]
Awesome!
